language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - "pip install -r requirements.txt --use-mirrors"
  - "chmod +x ./cshcsite/manage.py"
# # command to run tests
script: ./cshcsite/manage.py test
notifications:
  email:
    recipients:
      - graham@grahammcculloch.co.uk
    on_success: change
    on_failure: always
