language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - "pip install -r requirements.txt --use-mirrors"
# # command to run tests
script: ./cshcsite/manage.py test
notifications:
  email:
    recipients:
      - simon@jellypig.co.uk
      - graham@grahammcculloch.co.uk
      - matt.kern@undue.org
    on_success: change
    on_failure: always
