language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
DJANGO_VERSION=1.4.3
# command to install dependencies
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# # command to run tests
script: ./django.sh test club
