echo Migrating models
manage.py convert_to_south core
manage.py convert_to_south venues
manage.py convert_to_south competitions
manage.py convert_to_south teams
manage.py convert_to_south opposition
manage.py convert_to_south members
manage.py convert_to_south matches
manage.py convert_to_south awards
manage.py convert_to_south training
manage.py convert_to_south feedback
