echo Creating initial schema migrations
python manage.py schemamigration core --initial
python manage.py schemamigration venues --initial
python manage.py schemamigration competitions --initial
python manage.py schemamigration teams --initial
python manage.py schemamigration opposition --initial
python manage.py schemamigration members --initial
python manage.py schemamigration matches --initial
python manage.py schemamigration awards --initial
python manage.py schemamigration training --initial
