from club.models import *
from django.contrib import admin

admin.site.register(Club)
admin.site.register(League)
admin.site.register(Division)
admin.site.register(Team)
admin.site.register(Player)
admin.site.register(Season)
admin.site.register(DivisionSeason)
admin.site.register(DivisionMatch)
admin.site.register(Venue)
admin.site.register(Cup)
admin.site.register(CupSeason)
admin.site.register(CupMatch)
admin.site.register(FriendlyMatch)
admin.site.register(TeamCaptaincy)
admin.site.register(ClubAffiliation)
admin.site.register(DivisionParticipation)
admin.site.register(CupParticipation)
admin.site.register(Appearance)
admin.site.register(MatchAward)
admin.site.register(EndOfSeasonAward)
admin.site.register(MatchAwardWinner)
admin.site.register(EndOfSeasonAwardWinner)